# Generated by Django 4.1.3 on 2022-12-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('teudat_zeut', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('vip', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('phone1', models.CharField(max_length=10)),
                ('phone2', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('birth_date', models.CharField(max_length=10)),
                ('reg_date', models.CharField(max_length=10)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
    ]
