# Generated by Django 4.1.3 on 2022-12-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_id', models.CharField(max_length=10)),
                ('affiliate_name', models.CharField(max_length=20)),
                ('parent_company', models.CharField(max_length=20)),
                ('staff_ids', models.CharField(max_length=100)),
                ('affiliate_country', models.CharField(max_length=20)),
                ('affiliate_city', models.CharField(max_length=20)),
                ('affiliate_location', models.CharField(max_length=50)),
                ('affiliate_percent', models.CharField(max_length=2)),
                ('phone1', models.CharField(max_length=13)),
                ('phone2', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=30)),
                ('site', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=15)),
                ('contact_id', models.CharField(max_length=10)),
                ('reg_date', models.CharField(max_length=20)),
            ],
        ),
    ]
