# Generated by Django 4.1.3 on 2022-12-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.CharField(max_length=10)),
                ('item_id', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('item_firm', models.CharField(max_length=20)),
                ('item_barcode', models.CharField(max_length=60)),
                ('input_cost', models.CharField(max_length=4)),
                ('output_cost', models.CharField(max_length=4)),
                ('creation_date', models.CharField(max_length=20)),
                ('exp_date', models.CharField(max_length=20)),
                ('package_num', models.CharField(max_length=20)),
                ('item_count', models.CharField(max_length=6)),
                ('in_stock', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='age',
        ),
        migrations.AddField(
            model_name='lead',
            name='address',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='birth_date',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='country',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='family_ids',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='phone1',
            field=models.CharField(default='', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='phone2',
            field=models.CharField(default='', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='reg_date',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='teudat_zeut',
            field=models.CharField(default='', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='user_id',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='username',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='vip',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='first_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_name',
            field=models.CharField(max_length=10),
        ),
    ]
